// Code generated by Kitex v0.8.0. DO NOT EDIT.
package srv

import (
	server "github.com/cloudwego/kitex/server"
	post "github.com/cold-runner/Hylark/kitex_gen/post"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler post.Srv, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
