version: '3.1'

services:
  redis:
    image: "redis:7.2"
    ports:
      - "6379:6379"
  db:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
    volumes:
      - ../../script/lark.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  user_service:
    build:
      context: ../../
      dockerfile: internal/user/Dockerfile
    depends_on:
      - db
      - redis
    command: ["wait-for-it.sh", "db:3306", "--", "app"]
    ports:
      - "8888:8888"
