version: '3.1'

services:
  redis:
    image: "redis:7.2"
    ports:
      - "6379:6379"
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
    volumes:
      - ../../script/post.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  search-engine:
    image: "public.ecr.aws/zinclabs/zincsearch"
    environment:
      ZINC_DATA_PATH: /data
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: Complexpass#123
    volumes:
      - ./zinc/data:/data
    ports:
      - "4080:4080"

  post_service:
    build:
      context: ../../
      dockerfile: internal/post/Dockerfile
    depends_on:
      - db
      - redis
      - search-engine
    command: ["wait-for-it.sh", "db:3306", "--", "app"]
    ports:
      - "8888:8888"
